project:
  type: website

website:
  title: "Parker Max"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "GitHub"
        href: GitHub.qmd
      - text: "R Tip of the Day"
        href: RTip.qmd
      - text: "Mini-Project 1: Maps"
        href: mini-project1.qmd
      - text: "Mini-Project 2: Data Acquisition"
        href: mini-project2.qmd
format:
  html:
    theme: cosmo
    toc: true
