project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Parker Max"
  favicon: images/DSC07483.JPG
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: GitHub.qmd
        text: GitHub
      - href: RTip.qmd
        text: R Tip of the Day
      - text: Mini-Projects
        menu:
          - href: mini-project1.qmd
            text: "Mini-Project 1: Maps"
          - href: mini-project2.qmd
            text: "Mini-Project 2: Data Acquisition"

format:
  html:
    theme: [yeti, theme.scss] 
    toc: true
    code-overflow: wrap

editor: visual
