project:
  type: website
  output-dir:  docs

website:
  title: "Parker-Max-264"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - GitHub.qmd
      - Projects.qmd
      - About.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

